import express, { type Request, type Response, type NextFunction } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import { pinoHttp } from 'pino-http';
import { randomInt, randomUUID } from 'node:crypto';
import path from 'node:path';
import { z, ZodError } from 'zod';
import { config } from './config.js';
import { AppError, assert } from './errors.js';
import { createStore, type Store, type TourFilters, type CreateTour, type UpdateTour, type BookingStatus, type Booking, type ContentType, type ContentStatus } from './store.js';
import { hashOtp, hashPassword, issueSession, normalizeIdentity, setAuthCookies, clearAuthCookies, verifyOtpHash, verifyPassword, verifyToken, REFRESH_COOKIE } from './security.js';
import { TravelProvider, MessagingProvider, PaymentProvider, type Vertical } from './providers.js';
import { optionalAuth, requireAuth, requireAdmin, requirePermission, permissionsFor, notFound, requestContext } from './middleware.js';
import { rateLimit } from './rate-limit.js';
import { SECRET_MASK } from './secrets.js';
import { MediaService, optimizedMediaUrl } from './media.js';

const verticalSchema = z.enum(['flight', 'hotel', 'home', 'visa', 'esim', 'tour']);
const tourStatusSchema = z.enum(['draft', 'published', 'archived']);
const bookingStatusSchema = z.enum(['new', 'reviewing', 'accepted', 'processing', 'pending', 'confirmed', 'completed', 'rejected', 'cancelled', 'failed']);
const contentTypeSchema = z.enum(['homepage', 'destination', 'hotel', 'home', 'visa', 'esim', 'offer', 'airline', 'banner', 'faq', 'company']);
const contentStatusSchema = z.enum(['draft', 'published', 'archived']);
const tourInputSchema = z.object({ slug: z.string().trim().min(3).max(160).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), title: z.string().trim().min(3).max(180), country: z.string().trim().min(2).max(80), tourType: z.string().trim().min(2).max(80), destinations: z.array(z.string().trim().min(1).max(80)).min(1).max(20), durationDays: z.number().int().positive().max(60), durationNights: z.number().int().nonnegative().max(59), description: z.string().max(3000).default(''), imageUrl: z.string().max(500).default(''), mediaId: z.string().uuid().optional(), priceBdt: z.number().nonnegative().max(100000000), status: tourStatusSchema.default('draft'), featured: z.boolean().default(false) });
const tourPatchSchema = tourInputSchema.partial();
const identityRequest = z.object({ identity: z.string().min(3).max(160), fullName: z.string().trim().min(2).max(100).optional(), adminOnly: z.boolean().default(false) });
const verifyOtpRequest = z.object({ challengeId: z.string().uuid(), code: z.string().regex(/^\d{6}$/, 'OTP must be a 6 digit code') });
const bookingRequest = z.object({ vertical: verticalSchema, payload: z.unknown() });
const tourBookingPayload = z.object({ tourId: z.string().uuid(), travellers: z.number().int().min(1).max(30), travelDate: z.string().min(8).max(30) }).passthrough();
const paymentRequest = z.object({ bookingId: z.string().uuid(), amount: z.number().positive().max(10_000_000), currency: z.string().length(3).default('BDT') });
const supportRequest = z.object({ name: z.string().trim().min(2).max(120), mobile: z.string().trim().min(7).max(30), email: z.string().email(), subject: z.string().trim().min(2).max(180) });
const supportPatchRequest = z.object({ status: z.enum(['open', 'pending', 'in_progress', 'waiting_customer', 'resolved', 'closed']).optional(), priority: z.enum(['low', 'normal', 'high', 'urgent']).optional(), assignedTo: z.string().uuid().nullable().optional() }).strict();
const supportMessageRequest = z.object({ message: z.string().trim().min(1).max(4000), internal: z.boolean().default(false) });
const customerNoteRequest = z.object({ note: z.string().trim().min(1).max(4000) });
const preferencesPatchRequest = z.object({ marketingEmailOptIn: z.boolean().optional(), marketingSmsOptIn: z.boolean().optional(), marketingInAppOptIn: z.boolean().optional() }).strict();
const profilePatchRequest = z.object({ fullName: z.string().trim().min(2).max(120).optional(), avatarUrl: z.string().url().or(z.literal('')).optional(), avatarMediaId: z.string().uuid().nullable().optional(), marketingEmailOptIn: z.boolean().optional(), marketingSmsOptIn: z.boolean().optional(), marketingInAppOptIn: z.boolean().optional() }).strict();
const changePasswordRequest = z.object({ currentPassword: z.string().min(8).max(200), newPassword: z.string().min(12).max(200), confirmPassword: z.string().min(12).max(200) });
const contactOtpRequest = z.object({ target: z.string().min(3).max(160), currentPassword: z.string().min(8).max(200) });
const verifyContactOtpRequest = z.object({ challengeId: z.string().uuid(), code: z.string().regex(/^\d{6}$/) });
const serviceStatusSchema = z.enum(['active', 'hidden', 'maintenance', 'archived']);
const paymentStatusSchema = z.enum(['created', 'pending', 'paid', 'failed', 'refunded', 'partially_refunded']);
const trackBookingRequest = z.object({ bookingReference: z.string().uuid(), identity: z.string().min(3).max(160) });
const notificationRequest = z.object({ userId: z.string().optional(), identity: z.string().optional(), allUsers: z.boolean().default(false), confirmMassSend: z.boolean().default(false), title: z.string().trim().min(2).max(160), message: z.string().trim().min(2).max(4000), channels: z.array(z.enum(['in_app', 'sms', 'email'])).min(1).default(['in_app']) });
const isSafeBrandLogo = (value: string) => { if (!value) return true; if (value.startsWith('/')) return true; try { const url = new URL(value); return url.protocol === 'http:' || url.protocol === 'https:'; } catch { return false; } };
const settingPatchSchema = z.object({ brand_name: z.string().max(120).optional(), brand_logo_url: z.string().max(500).refine(isSafeBrandLogo, 'Logo URL must be an https URL or a local path').optional(), support_email: z.string().email().or(z.literal('')).optional(), support_phone: z.string().max(40).optional(), feature_flights: z.union([z.boolean(), z.enum(['true','false'])]).optional(), feature_hotels: z.union([z.boolean(), z.enum(['true','false'])]).optional(), feature_homes: z.union([z.boolean(), z.enum(['true','false'])]).optional(), feature_visa: z.union([z.boolean(), z.enum(['true','false'])]).optional(), feature_tours: z.union([z.boolean(), z.enum(['true','false'])]).optional(), feature_esim: z.union([z.boolean(), z.enum(['true','false'])]).optional(), payment_provider: z.enum(['sslcommerz', 'bkash']).optional(), payment_webhook_secret: z.string().max(500).optional(), sslcommerz_store_id: z.string().max(160).optional(), sslcommerz_store_password: z.string().max(500).optional(), sslcommerz_api_url: z.string().url().or(z.literal('')).optional(), sslcommerz_validation_url: z.string().url().or(z.literal('')).optional(), sslcommerz_ipn_url: z.string().url().or(z.literal('')).optional(), bkash_base_url: z.string().url().or(z.literal('')).optional(), bkash_app_key: z.string().max(500).optional(), bkash_app_secret: z.string().max(500).optional(), bkash_username: z.string().max(200).optional(), bkash_password: z.string().max(500).optional(), sms_provider: z.enum(['custom_gateway', 'bulksmsbd']).optional(), sms_gateway_url: z.string().url().or(z.literal('')).optional(), sms_gateway_username: z.string().max(200).optional(), sms_gateway_password: z.string().max(500).optional(), sms_api_key: z.string().max(500).optional(), sms_sender_id: z.string().max(120).optional(), smtp_host: z.string().max(200).optional(), smtp_port: z.coerce.number().int().min(1).max(65535).optional(), smtp_user: z.string().max(240).optional(), smtp_password: z.string().max(500).optional(), smtp_from: z.string().email().or(z.literal('')).optional(), travel_provider_url: z.string().url().or(z.literal('')).optional(), travel_provider_api_key: z.string().max(500).optional() }).strict();
const roleRequest = z.object({ role: z.enum(['customer', 'manager', 'admin', 'super_admin', 'support', 'content_manager', 'finance']) });
const passwordLoginRequest = z.object({ identity: z.string().email(), password: z.string().min(8).max(200) });
const messageTestRequest = z.object({ destination: z.string().min(3).max(240), subject: z.string().max(160).optional(), message: z.string().min(1).max(4000) });
const adminBookingPatchRequest = z.object({ status: bookingStatusSchema.optional(), internalNote: z.string().max(4000).optional(), ownerId: z.string().uuid().nullable().optional(), request: z.record(z.unknown()).optional() }).strict();
const contentInputSchema = z.object({ type: contentTypeSchema, slug: z.string().trim().min(2).max(160).regex(/^[a-z0-9]+(?:-[a-z0-9-]+)*$/), title: z.string().trim().min(2).max(180), subtitle: z.string().max(300).optional(), description: z.string().max(5000).optional(), imageUrl: z.string().max(500).optional(), mediaId: z.string().uuid().optional(), metadata: z.record(z.unknown()).default({}), status: contentStatusSchema.default('draft'), sortOrder: z.number().int().min(-100000).max(100000).default(0) });
const contentPatchSchema = contentInputSchema.partial();
const mediaFolderSchema = z.enum(['banners','tours','hotels','homes','destinations','services','testimonials','logos','general']);
const mediaPatchSchema = z.object({ altText: z.string().max(300).optional(), status: z.enum(['active','archived']).optional() }).strict();
const navigationInputSchema = z.object({ groupName: z.string().trim().min(1).max(80), parentId: z.string().uuid().nullable().optional(), label: z.string().trim().min(1).max(120), route: z.string().regex(/^\/admin(?:[/?].*)?$/), icon: z.string().trim().min(1).max(40), permission: z.string().max(80).optional(), sortOrder: z.number().int().min(-100000).max(100000).default(0), visible: z.boolean().default(true), enabled: z.boolean().default(true) });
const navigationPatchSchema = navigationInputSchema.partial();
const navigationReorderSchema = z.object({ ids: z.array(z.string().uuid()).min(1).max(500) });
const agentInputSchema = z.object({ fullName: z.string().trim().min(2).max(160), photoUrl: z.string().url().or(z.literal('')).optional(), mediaId: z.string().uuid().nullable().optional(), jobTitle: z.string().max(120).optional(), department: z.string().max(120).optional(), phone: z.string().max(40).optional(), whatsapp: z.string().max(40).optional(), email: z.string().email().or(z.literal('')).optional(), officeLocation: z.string().max(200).optional(), shortBio: z.string().max(500).optional(), fullDescription: z.string().max(5000).optional(), languages: z.array(z.string().max(60)).max(20).default([]), experienceYears: z.number().int().min(0).max(80).optional(), specialization: z.string().max(160).optional(), workingHours: z.string().max(160).optional(), status: z.enum(['active','hidden','archived']).default('active'), featured: z.boolean().default(false), displayOrder: z.number().int().min(-100000).max(100000).default(0) });
const agentPatchSchema = agentInputSchema.partial();
const campaignInputSchema = z.object({ name:z.string().trim().min(2).max(160), channels:z.array(z.enum(['email','sms','in_app'])).min(1), subject:z.string().max(200).optional(), preheader:z.string().max(300).optional(), senderName:z.string().max(160).optional(), senderEmail:z.string().email().or(z.literal('')).optional(), emailHtml:z.string().max(100000).optional(), emailText:z.string().max(10000).optional(), smsMessage:z.string().max(1000).optional(), webTitle:z.string().max(160).optional(), webMessage:z.string().max(4000).optional(), webCtaText:z.string().max(100).optional(), webCtaUrl:z.string().url().or(z.literal('')).optional(), segmentId:z.string().uuid().nullable().optional(), recipientFilter:z.record(z.unknown()).default({}), scheduledAt:z.string().datetime().optional(), timezone:z.string().max(80).optional(), status:z.enum(['draft','scheduled']).default('draft') });
const campaignPatchSchema = campaignInputSchema.partial();
const campaignTestSchema = z.object({ channel:z.enum(['email','sms','in_app']), destination:z.string().min(3).max(240).optional() });
const templateInputSchema = z.object({ name:z.string().trim().min(2).max(160), type:z.enum(['email','sms','in_app']), subject:z.string().max(200).optional(), content:z.string().max(100000), metadata:z.record(z.unknown()).default({}), status:z.enum(['active','archived']).default('active') });
const segmentInputSchema = z.object({ name:z.string().trim().min(2).max(160), description:z.string().max(500).optional(), rules:z.record(z.unknown()).default({}), status:z.enum(['active','archived']).default('active') });
const FEATURE_KEYS = ['feature_flights','feature_hotels','feature_homes','feature_visa','feature_tours','feature_esim'];
const SETTING_KEYS = ['brand_name','brand_logo_url','support_email','support_phone','payment_provider','payment_webhook_secret','sslcommerz_store_id','sslcommerz_store_password','sslcommerz_api_url','sslcommerz_validation_url','sslcommerz_ipn_url','bkash_base_url','bkash_app_key','bkash_app_secret','bkash_username','bkash_password','sms_provider','sms_gateway_url','sms_gateway_username','sms_gateway_password','sms_api_key','sms_sender_id','smtp_host','smtp_port','smtp_user','smtp_password','smtp_from','travel_provider_url','travel_provider_api_key',...FEATURE_KEYS];
const SETTING_SECRET_KEYS = new Set(['sslcommerz_store_password','payment_webhook_secret','sslcommerz_api_key','bkash_app_key','bkash_app_secret','bkash_username','bkash_password','bkash_token','sms_api_key','sms_gateway_username','sms_gateway_password','smtp_password','travel_provider_api_key','payment_provider_api_key']);
const ADMIN_ROLES = ['admin', 'manager', 'super_admin', 'support', 'content_manager', 'finance'] as const;
const PRIVILEGED_ROLES = ['admin', 'super_admin'] as const;
const CONTENT_ROLES = ['admin', 'super_admin', 'content_manager'] as const;
const FINANCE_ROLES = ['admin', 'super_admin', 'finance'] as const;
const SUPPORT_ROLES = ['admin', 'super_admin', 'support', 'manager'] as const;
const SAFE_PROVIDER_ERROR_CODES = new Set(['MEDIA_NOT_CONFIGURED','MEDIA_UPLOAD_FAILED','MEDIA_DELETE_FAILED','IMAGE_TOO_LARGE','UNSUPPORTED_IMAGE_FORMAT','IMAGE_UPLOAD_INVALID','PROVIDER_NOT_CONFIGURED','PROVIDER_UNAVAILABLE','PROVIDER_ERROR','PROVIDER_TIMEOUT','SMS_NOT_CONFIGURED','SMS_PROVIDER_ERROR','EMAIL_NOT_CONFIGURED','SSLCOMMERZ_NOT_CONFIGURED','SSLCOMMERZ_ERROR','BKASH_NOT_CONFIGURED','BKASH_AUTH_ERROR','BKASH_ERROR','REFUNDS_NOT_CONFIGURED','NOTIFICATION_RETRY_FAILED']);

const toInput = (schema: z.ZodTypeAny, value: unknown) => {
  try { return schema.parse(value); } catch (error) { if (error instanceof ZodError) throw new AppError(400, 'VALIDATION_ERROR', 'Please check the submitted fields', error.flatten()); throw error; }
};
const clientMeta = (req: Request) => ({ ip: req.ip, userAgent: req.get('user-agent')?.slice(0, 500) });
const sanitizeEmailHtml = (value?: string) => value?.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<iframe[\s\S]*?<\/iframe>/gi,'').replace(/<object[\s\S]*?<\/object>/gi,'').replace(/<embed[^>]*>/gi,'').replace(/\son[a-z]+\s*=\s*(["']).*?\1/gi,'').replace(/javascript:/gi,'') || undefined;
const errorPageHtml = (status: number) => { const copy: Record<number, [string, string]> = { 403: ['Access restricted', 'You do not have permission to view this page.'], 404: ['Page not found', 'The page you are looking for does not exist or has moved.'], 503: ['Temporarily unavailable', 'We are having trouble reaching a required service. Please try again shortly.'], 500: ['Something went wrong', 'We are having trouble loading this page. Please try again.'] }; const [title, message] = copy[status] || copy[500]; return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Sadik Travels</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f5f7fb;color:#17253b;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}.card{width:min(460px,calc(100% - 36px));padding:38px 30px;text-align:center;background:#fff;border:1px solid #e3e8f0;border-radius:18px;box-shadow:0 24px 70px rgba(16,36,80,.12)}.code{font-size:12px;letter-spacing:.15em;text-transform:uppercase;color:#1438b8;font-weight:800}.logo{width:72px;height:55px;object-fit:contain}.card h1{font-size:28px;line-height:1.2;margin:14px 0 8px}.card p{color:#68758a;font-size:13px;line-height:1.6;margin:0 auto 24px}.actions{display:flex;justify-content:center;gap:9px;flex-wrap:wrap}.actions a{display:inline-flex;padding:10px 16px;border-radius:8px;text-decoration:none;font-size:12px;font-weight:800;border:1px solid #cbd5e4;color:#17253b}.actions a.primary{background:#1438b8;border-color:#1438b8;color:#fff}</style></head><body><main class="card"><img class="logo" src="/assets/sadik-travels-logo.png?v=3" alt="Sadik Travels"><div class="code">Error ${status}</div><h1>${title}</h1><p>${message}</p><div class="actions"><a class="primary" href="/">Go home</a><a href="/">Try again</a></div></main></body></html>`; };
const isPrivileged = (req: Request) => PRIVILEGED_ROLES.includes(req.user?.role as typeof PRIVILEGED_ROLES[number]);
const assertPrivileged = (req: Request) => assert(isPrivileged(req), 403, 'ADMIN_ONLY', 'Only an admin can perform this operation');
const bookingTransitions: Record<BookingStatus, BookingStatus[]> = {
  new: ['reviewing', 'accepted', 'rejected', 'cancelled'],
  reviewing: ['new', 'accepted', 'rejected', 'cancelled'],
  accepted: ['processing', 'rejected', 'cancelled'],
  processing: ['confirmed', 'rejected', 'cancelled'],
  pending: ['reviewing', 'accepted', 'processing', 'confirmed', 'rejected', 'cancelled'],
  confirmed: ['completed', 'cancelled'],
  completed: [],
  rejected: [],
  cancelled: [],
  failed: ['reviewing', 'cancelled']
};

export function buildApp() {
  const { store } = createStore();
  const travel = new TravelProvider(store);
  const messaging = new MessagingProvider(store);
  const payment = new PaymentProvider(store);
  const media = new MediaService();
  const mediaUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: config.mediaMaxUploadBytes, files: 1 }, fileFilter: (_req, file, callback) => { if (!['image/jpeg','image/png','image/webp'].includes(file.mimetype)) callback(new AppError(415, 'UNSUPPORTED_IMAGE_FORMAT', 'Unsupported image format')); else callback(null, true); } });
  const app = express();
  app.disable('x-powered-by');
  app.set('trust proxy', config.trustProxy);

  app.use(pinoHttp({ level: config.logLevel, redact: ['req.headers.authorization', 'req.headers.cookie', 'res.headers["set-cookie"]'] }));
  app.use(requestContext());
  app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' }, contentSecurityPolicy: { directives: { imgSrc: ["'self'", 'data:', 'https:'], fontSrc: ["'self'", 'https:', 'data:'], styleSrc: ["'self'", 'https:', "'unsafe-inline'"], scriptSrc: ["'self'"] } } }));
  const corsMiddleware = cors({ origin: (origin, callback) => { if (!origin || config.corsOrigins.includes(origin)) callback(null, true); else callback(new AppError(403, 'CORS_DENIED', 'Origin is not allowed')); }, credentials: true, methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'], allowedHeaders: ['Content-Type', 'Authorization', 'X-Request-ID'] });
  app.use((req, res, next) => { const origin = req.get('origin'); let sameOrigin = !origin; if (origin) { try { sameOrigin = new URL(origin).host === req.get('host'); } catch { /* Invalid origins are handled by CORS. */ } } if (sameOrigin) return next(); return corsMiddleware(req, res, next); });
  app.use(express.json({ limit: '1mb', verify: (req, _res, buffer) => { (req as any).rawBody = Buffer.from(buffer); } }));
  app.use(cookieParser());
  app.use(rateLimit('global', 300, 60));

  app.get(['/healthz', '/api/health'], async (_req, res, next) => { try { await store.health(); res.json({ status: 'ok', ok: true, service: 'sadik-travels-api', database: 'connected', env: config.nodeEnv }); } catch (error) { next(new AppError(503, 'NOT_READY', 'Service dependencies are not ready', config.isProduction ? undefined : error)); } });
  app.get(['/readyz', '/api/ready'], async (_req, res, next) => { try { await store.health(); res.json({ ok: true, database: 'sqlite' }); } catch (error) { next(new AppError(503, 'NOT_READY', 'Service dependencies are not ready', config.isProduction ? undefined : error)); } });
  app.get('/api/v1/site/settings', async (_req, res) => {
    const serviceVisibility = await store.getServiceVisibility();
    const serviceStatuses = Object.fromEntries(serviceVisibility.map(item => [item.key, item.status]));
    const features: Record<string, boolean> = {};
    for (const key of FEATURE_KEYS) { const serviceKey = key.replace('feature_', ''); const status = serviceStatuses[serviceKey] ?? 'active'; features[serviceKey] = status !== 'hidden' && status !== 'archived'; }
    const savedLogo = await store.getSetting('brand_logo_url');
    const logoUrl = savedLogo && !savedLogo.includes('SqrRwJyv') ? savedLogo : '/assets/sadik-travels-logo.png?v=3';
    res.json({ brand: await store.getSetting('brand_name') || 'Sadik Travels', logoUrl, support: { email: await store.getSetting('support_email') || '', phone: await store.getSetting('support_phone') || '' }, features, serviceStatuses });
  });
  app.get('/api/v1/site/content', async (req, res) => { const type = contentTypeSchema.safeParse(String(req.query.type || 'all')); const content = await store.listContent({ type: type.success ? type.data : 'all', q: req.query.q ? String(req.query.q) : undefined }); res.json({ content: content.map(item => ({ ...item, imageUrl: optimizedMediaUrl(item.imageUrl, { width: 1600 }) })) }); });
  app.get('/api/v1/site/agents', async (req, res) => { const result = await store.listTravelAgents({ publicOnly: true, featured: req.query.featured === 'true' ? true : undefined, page: Number(req.query.page) || 1, pageSize: Number(req.query.pageSize) || 50 }); res.json({ agents: result.agents.map(agent => ({ ...agent, photoUrl: optimizedMediaUrl(agent.photoUrl, { width: 800 }) })) }); });

  // Authentication: Bangladesh phone OTP first, email OTP as a fallback.
  app.post('/api/v1/auth/password-login', rateLimit('password-login', 10, 300), async (req, res) => { const input = toInput(passwordLoginRequest, req.body); const identity = normalizeIdentity(input.identity).identity; const user = await store.findUserByIdentity(identity); assert(user && ADMIN_ROLES.includes(user.role as typeof ADMIN_ROLES[number]) && user.status === 'active', 401, 'ADMIN_LOGIN_INVALID', 'Invalid admin credentials'); const hash = await store.getPasswordHash(identity); assert(hash && await verifyPassword(input.password, hash), 401, 'ADMIN_LOGIN_INVALID', 'Invalid admin credentials'); const session = await issueSession(store, user, clientMeta(req)); await store.updateLastLogin(user.id, req.ip); setAuthCookies(res, session.accessToken, session.refreshToken); await store.audit('auth.password_login', { ...clientMeta(req), userId: user.id }); res.json({ accessToken: session.accessToken, expiresIn: config.accessTokenTtl, user }); });

  app.post('/api/v1/auth/request-otp', rateLimit('otp', 5, 300), async (req, res) => {
    const input = toInput(identityRequest, req.body);
    const normalized = normalizeIdentity(input.identity);
    if (input.adminOnly && !config.adminIdentities.includes(normalized.identity)) throw new AppError(403, 'ADMIN_NOT_WHITELISTED', 'This identity is not authorized for admin login');
    const recent = await store.countRecentOtpRequests(normalized.identity, new Date(Date.now() - 60_000));
    assert(recent < 3, 429, 'OTP_THROTTLED', 'Please wait before requesting another code');
    const code = String(randomInt(100000, 1_000_000));
    const challengeId = randomUUID();
    await store.createOtp({ id: challengeId, identity: normalized.identity, channel: normalized.channel, codeHash: await hashOtp(code), attempts: 0, maxAttempts: 5, expiresAt: new Date(Date.now() + 5 * 60_000).toISOString(), requestIp: req.ip });
    const delivery = await messaging.sendOtp(normalized.channel, normalized.identity, code);
    await store.audit('auth.otp_requested', { ...clientMeta(req), metadata: { channel: normalized.channel } });
    res.status(202).json({ challengeId, channel: normalized.channel, maskedDestination: normalized.channel === 'sms' ? `${normalized.identity.slice(0, 7)}••••` : `${normalized.identity.slice(0, 2)}•••${normalized.identity.slice(normalized.identity.indexOf('@'))}`, expiresIn: 300, ...(delivery.devCode && !config.isProduction ? { devCode: delivery.devCode } : {}) });
  });

  app.post('/api/v1/auth/verify-otp', rateLimit('otp-verify', 15, 300), async (req, res) => {
    const input = toInput(verifyOtpRequest, req.body);
    const challenge = await store.findOtp(input.challengeId);
    assert(challenge, 404, 'OTP_NOT_FOUND', 'This verification code is no longer available');
    assert(!challenge.consumedAt, 400, 'OTP_USED', 'This verification code has already been used');
    assert(new Date(challenge.expiresAt) > new Date(), 400, 'OTP_EXPIRED', 'This verification code has expired');
    assert(challenge.attempts < challenge.maxAttempts, 429, 'OTP_LOCKED', 'Too many incorrect attempts');
    const valid = await verifyOtpHash(input.code, challenge.codeHash);
    if (!valid) { const updated = await store.incrementOtpAttempts(challenge.id); const remaining = Math.max(0, (updated?.maxAttempts ?? challenge.maxAttempts) - (updated?.attempts ?? challenge.attempts + 1)); throw new AppError(400, 'OTP_INVALID', remaining ? `Incorrect code. ${remaining} attempt${remaining === 1 ? '' : 's'} remaining.` : 'Too many incorrect attempts'); }
    await store.consumeOtp(challenge.id);
    const isConfiguredAdmin = config.adminIdentities.includes(challenge.identity);
    let user = await store.findUserByIdentity(challenge.identity);
    if (!user) user = await store.createUser({ identity: challenge.identity, channel: challenge.channel, role: isConfiguredAdmin ? 'admin' : 'customer' });
    else if (isConfiguredAdmin && !['admin', 'super_admin'].includes(user.role)) user = (await store.setUserRole(user.id, 'admin')) ?? user;
    const session = await issueSession(store, user, clientMeta(req));
    await store.updateLastLogin(user.id, req.ip);
    setAuthCookies(res, session.accessToken, session.refreshToken);
    await store.audit('auth.login', { ...clientMeta(req), userId: user.id, metadata: { channel: challenge.channel } });
    res.json({ accessToken: session.accessToken, expiresIn: config.accessTokenTtl, user });
  });

  app.post('/api/v1/auth/refresh', rateLimit('refresh', 30, 60), async (req, res) => {
    const token = req.cookies?.[REFRESH_COOKIE] as string | undefined;
    if (!token) throw new AppError(401, 'AUTH_REQUIRED', 'Refresh login is required');
    const claims = await verifyToken(token, 'refresh');
    const existing = await store.findSessionByRefreshJti(claims.jti);
    assert(existing && existing.id === claims.sid && existing.userId === claims.sub && !existing.revokedAt && new Date(existing.expiresAt) > new Date(), 401, 'SESSION_INVALID', 'Your session has expired. Please login again.');
    const user = await store.findUserById(existing.userId);
    assert(user && user.status === 'active', 403, 'ACCOUNT_UNAVAILABLE', 'This account is not available');
    await store.revokeSession(existing.id);
    const next = await issueSession(store, user, clientMeta(req));
    setAuthCookies(res, next.accessToken, next.refreshToken);
    res.json({ accessToken: next.accessToken, expiresIn: config.accessTokenTtl, user });
  });
  app.post('/api/v1/auth/logout', async (req, res, next) => { try { const token = req.cookies?.[REFRESH_COOKIE] as string | undefined; if (token) { try { const claims = await verifyToken(token, 'refresh'); await store.revokeSession(claims.sid); await store.audit('auth.logout', { ...clientMeta(req), userId: claims.sub }); } catch { /* Always clear local cookies. */ } } clearAuthCookies(res); res.status(204).send(); } catch (error) { next(error); } });
  app.get('/api/v1/auth/me', requireAuth(store), (req, res) => res.json({ user: req.user }));
  app.get('/api/v1/account/preferences', requireAuth(store), async (req,res)=>{const user=await store.findUserById(req.user!.id);res.json({preferences:{marketingEmailOptIn:user?.marketingEmailOptIn!==false,marketingSmsOptIn:user?.marketingSmsOptIn!==false,marketingInAppOptIn:user?.marketingInAppOptIn!==false}});});
  app.patch('/api/v1/account/preferences', requireAuth(store), async (req,res)=>{const input=toInput(preferencesPatchRequest,req.body);const user=await store.updateUserProfile(req.user!.id,input);assert(user,404,'USER_NOT_FOUND','Account not found');await store.audit('account.preferences_updated',{...clientMeta(req),userId:req.user!.id,metadata:{keys:Object.keys(input)}});res.json({preferences:{marketingEmailOptIn:user.marketingEmailOptIn!==false,marketingSmsOptIn:user.marketingSmsOptIn!==false,marketingInAppOptIn:user.marketingInAppOptIn!==false}});});
  app.get('/api/v1/notifications', requireAuth(store), async (req, res) => { const notifications = await store.listNotifications(req.user!.id); res.json({ notifications, unread: notifications.filter(item => !item.readAt).length }); });
  app.patch('/api/v1/notifications/:id/read', requireAuth(store), async (req, res) => { const notification = await store.markNotificationRead(String(req.params.id), req.user!.id); assert(notification, 404, 'NOTIFICATION_NOT_FOUND', 'Notification not found'); res.json({ notification }); });

  // Public tour catalogue and live provider search.
  app.get('/api/v1/tours', rateLimit('tour-catalog', 120, 60), optionalAuth(store), async (req, res) => { const filters: TourFilters = { q: req.query.q ? String(req.query.q) : undefined, country: req.query.destination ? String(req.query.destination) : undefined, tourType: req.query.tour_type ? String(req.query.tour_type) : undefined, maxPrice: req.query.max_price ? Number(req.query.max_price) : undefined, sort: req.query.sort === 'price_asc' || req.query.sort === 'price_desc' ? req.query.sort : 'newest' }; const tours = await store.listTours(filters); res.json({ success: true, filters, count: tours.length, tours: tours.map(tour => ({ ...tour, imageUrl: optimizedMediaUrl(tour.imageUrl, { width: 1200 }) })) }); });
  app.get('/api/v1/tours/:idOrSlug', rateLimit('tour-detail', 120, 60), async (req, res) => { const tour = await store.findTour(String(req.params.idOrSlug)); assert(tour && tour.status === 'published', 404, 'TOUR_NOT_FOUND', 'Tour package not found'); res.json({ tour: { ...tour, imageUrl: optimizedMediaUrl(tour.imageUrl, { width: 1200 }) } }); });
  app.post('/api/v1/search/:vertical', rateLimit('search', 90, 60), optionalAuth(store), async (req, res) => {
    const vertical = toInput(verticalSchema, String(req.params.vertical)) as Vertical;
    const payload = toInput(z.record(z.unknown()), req.body ?? {});
    if (vertical === 'tour') { const tours = await store.listTours({ q: typeof payload.q === 'string' ? payload.q : undefined, country: typeof payload.destination === 'string' ? payload.destination : undefined, tourType: typeof payload.tourType === 'string' ? payload.tourType : undefined, maxPrice: typeof payload.maxPrice === 'number' ? payload.maxPrice : undefined, sort: payload.sort === 'price_asc' || payload.sort === 'price_desc' ? payload.sort : 'newest' }); await store.audit('search.tour', { ...clientMeta(req), userId: req.user?.id, metadata: { keys: Object.keys(payload) } }); res.json({ success: true, vertical, searchId: `TOUR-${Date.now().toString(36).toUpperCase()}`, results: tours.map(tour => ({ ...tour, imageUrl: optimizedMediaUrl(tour.imageUrl, { width: 1200 }) })) }); return; }
    const raw = await travel.search(vertical, payload);
    const result = Array.isArray(raw) ? { results: raw } : (raw && typeof raw === 'object' ? raw : { results: [] });
    await store.audit(`search.${vertical}`, { ...clientMeta(req), userId: req.user?.id, metadata: { keys: Object.keys(payload) } });
    res.json({ success: true, vertical, ...result as Record<string, unknown> });
  });

  // Admin access and operational dashboard.
  app.get('/api/v1/admin/me', requireAdmin(store), (req, res) => res.json({ user: req.user, permissions: permissionsFor(req.user).map(permission => permission.replace(':', '_')) }));
  app.get('/api/v1/admin/navigation', requireAdmin(store), async (_req, res) => res.json({ navigation: await store.listNavigation(false) }));
  app.post('/api/v1/admin/navigation', requirePermission(store, 'navigation:manage'), async (req, res) => { const input=toInput(navigationInputSchema,req.body); const item=await store.createNavigation(input); await store.audit('admin.navigation_created',{...clientMeta(req),userId:req.user!.id,metadata:{navigationId:item.id,label:item.label}}); res.status(201).json({ navigation:item }); });
  app.patch('/api/v1/admin/navigation/:id', requirePermission(store, 'navigation:manage'), async (req,res)=>{ const input=toInput(navigationPatchSchema,req.body); const item=await store.updateNavigation(String(req.params.id),input); assert(item,404,'NAVIGATION_NOT_FOUND','Navigation item not found'); await store.audit('admin.navigation_updated',{...clientMeta(req),userId:req.user!.id,metadata:{navigationId:item.id,label:item.label,visible:item.visible}}); res.json({navigation:item}); });
  app.delete('/api/v1/admin/navigation/:id', requirePermission(store, 'navigation:manage'), async (req,res)=>{ const deleted=await store.deleteNavigation(String(req.params.id)); assert(deleted,404,'NAVIGATION_NOT_FOUND','Navigation item not found'); await store.audit('admin.navigation_deleted',{...clientMeta(req),userId:req.user!.id,metadata:{navigationId:req.params.id}}); res.json({deleted:true}); });
  app.post('/api/v1/admin/navigation/reorder', requirePermission(store, 'navigation:manage'), async (req,res)=>{ const input=toInput(navigationReorderSchema,req.body); await store.reorderNavigation(input.ids); await store.audit('admin.navigation_reordered',{...clientMeta(req),userId:req.user!.id,metadata:{count:input.ids.length}}); res.json({navigation:await store.listNavigation(false)}); });

  app.get('/api/v1/admin/profile', requireAdmin(store), async (req, res) => { const user = await store.findUserById(req.user!.id); assert(user, 404, 'USER_NOT_FOUND', 'Admin profile not found'); res.json({ user }); });
  app.patch('/api/v1/admin/profile', requireAdmin(store), async (req, res) => { const input = toInput(profilePatchRequest, req.body); const user = await store.updateUserProfile(req.user!.id, { ...input, avatarMediaId: input.avatarMediaId ?? undefined }); assert(user, 404, 'USER_NOT_FOUND', 'Admin profile not found'); await store.audit('admin.profile_updated', { ...clientMeta(req), userId: req.user!.id, metadata: { keys: Object.keys(input) } }); res.json({ user }); });
  app.post('/api/v1/admin/profile/change-password', requireAdmin(store), async (req, res) => { const input = toInput(changePasswordRequest, req.body); assert(input.newPassword === input.confirmPassword, 400, 'PASSWORD_MISMATCH', 'New passwords do not match'); assert(!input.newPassword.toLowerCase().includes('password'), 400, 'PASSWORD_WEAK', 'Choose a stronger password'); const identity = req.user!.email || req.user!.phone; assert(identity, 400, 'IDENTITY_MISSING', 'This admin account has no login identity'); const hash = await store.getPasswordHash(identity); assert(hash && await verifyPassword(input.currentPassword, hash), 401, 'CURRENT_PASSWORD_INVALID', 'Current password is incorrect'); await store.setPasswordHash(req.user!.id, await hashPassword(input.newPassword)); if (req.auth?.sid) await store.revokeOtherSessions(req.user!.id, req.auth.sid); await store.audit('admin.password_changed', { ...clientMeta(req), userId: req.user!.id }); res.json({ changed: true }); });
  app.post('/api/v1/admin/profile/request-contact-otp', requireAdmin(store), rateLimit('profile-contact-otp', 5, 300), async (req, res) => { const input = toInput(contactOtpRequest, req.body); const identity = req.user!.email || req.user!.phone; assert(identity, 400, 'IDENTITY_MISSING', 'This admin account has no login identity'); const hash = await store.getPasswordHash(identity); assert(hash && await verifyPassword(input.currentPassword, hash), 401, 'CURRENT_PASSWORD_INVALID', 'Current password is incorrect'); const normalized = normalizeIdentity(input.target); const existing = await store.findUserByIdentity(normalized.identity); assert(!existing || existing.id === req.user!.id, 409, 'IDENTITY_IN_USE', 'That contact is already used by another account'); const code = String(randomInt(100000, 1000000)); const challengeId = randomUUID(); await store.createOtp({ id: challengeId, identity: normalized.identity, channel: normalized.channel, codeHash: await hashOtp(code), attempts: 0, maxAttempts: 5, expiresAt: new Date(Date.now()+5*60_000).toISOString(), requestIp: req.ip, purpose: normalized.channel === 'email' ? 'profile_email_change' : 'profile_phone_change', userId: req.user!.id, targetIdentity: normalized.identity }); const delivery = await messaging.sendOtp(normalized.channel, normalized.identity, code); await store.audit('admin.contact_change_otp_requested', { ...clientMeta(req), userId: req.user!.id, metadata: { channel: normalized.channel } }); res.status(202).json({ challengeId, channel: normalized.channel, maskedDestination: normalized.channel === 'sms' ? `${normalized.identity.slice(0,7)}••••` : `${normalized.identity.slice(0,2)}•••${normalized.identity.slice(normalized.identity.indexOf('@'))}`, ...(delivery.devCode && !config.isProduction ? { devCode: delivery.devCode } : {}) }); });
  app.post('/api/v1/admin/profile/verify-contact-otp', requireAdmin(store), rateLimit('profile-contact-verify', 10, 300), async (req, res) => { const input = toInput(verifyContactOtpRequest, req.body); const challenge = await store.findOtp(input.challengeId); assert(challenge && challenge.userId === req.user!.id && challenge.targetIdentity && ['profile_email_change','profile_phone_change'].includes(challenge.purpose || ''), 404, 'OTP_NOT_FOUND', 'This contact verification is no longer available'); assert(!challenge.consumedAt && new Date(challenge.expiresAt)>new Date(), 400, 'OTP_EXPIRED', 'This verification code has expired'); assert(challenge.attempts < challenge.maxAttempts, 429, 'OTP_LOCKED', 'Too many incorrect attempts'); const valid = await verifyOtpHash(input.code, challenge.codeHash); if(!valid){await store.incrementOtpAttempts(challenge.id); throw new AppError(400,'OTP_INVALID','Incorrect verification code');} await store.consumeOtp(challenge.id); const patch = challenge.channel === 'email' ? { email: challenge.targetIdentity } : { phone: challenge.targetIdentity }; const user = await store.updateUserProfile(req.user!.id, patch); await store.audit(challenge.channel === 'email' ? 'admin.email_changed' : 'admin.phone_changed', { ...clientMeta(req), userId: req.user!.id, metadata: { channel: challenge.channel } }); res.json({ user }); });
  app.get('/api/v1/admin/profile/sessions', requireAdmin(store), async (req, res) => res.json({ sessions: await store.listSessions(req.user!.id), currentSessionId: req.auth?.sid }));
  app.post('/api/v1/admin/profile/sessions/revoke-others', requireAdmin(store), async (req, res) => { assert(req.auth?.sid, 401, 'SESSION_INVALID', 'Current session is not available'); await store.revokeOtherSessions(req.user!.id, req.auth.sid); await store.audit('admin.sessions_revoked', { ...clientMeta(req), userId: req.user!.id }); res.json({ revoked: true }); });
  app.get('/api/v1/admin/system-status', requirePermission(store, 'dashboard:view'), async (_req,res)=>{ await store.health(); const smsProvider=await store.getSetting('sms_provider')||config.smsProvider; const emailConfigured=Boolean((await store.getSetting('smtp_host'))||config.smtpHost) && Boolean((await store.getSetting('smtp_from'))||config.smtpFrom); const smsConfigured=smsProvider==='custom_gateway'?Boolean((await store.getSetting('sms_gateway_url'))||config.smsGatewayUrl):Boolean((await store.getSetting('sms_api_key'))||config.bulkSmsApiKey); const paymentConfigured=Boolean(await store.getSetting('sslcommerz_store_id')||await store.getSetting('bkash_base_url')); const travelConfigured=Boolean(await store.getSetting('travel_provider_url')||config.providerBaseUrl); res.json({services:{database:{status:'connected'},cloudinary:{status:media.isConfigured()?'connected':'not_configured'},email:{status:emailConfigured?'configured':'not_configured'},sms:{status:smsConfigured?'configured':'not_configured'},payment:{status:paymentConfigured?'configured':'not_configured'},travelApi:{status:travelConfigured?'configured':'not_configured'}}}); });
  app.get('/api/v1/admin/stats', requirePermission(store, 'dashboard:view'), async (_req, res) => { const stats = await store.adminStats(); const recent = await store.listAdminBookings({ page: 1, pageSize: 8 }); res.json({ ...stats, tours: stats.tours, recentBookings: recent.bookings, recentActivity: await store.listAuditLogs(12) }); });
  app.get('/api/v1/admin/activity', requirePermission(store, 'audit:view'), async (_req, res) => res.json({ activity: await store.listAuditLogs(50) }));
  app.get('/api/v1/admin/audit-logs', requirePermission(store, 'audit:view'), async (req, res) => res.json(await store.listAuditLogsDetailed({ q: req.query.q ? String(req.query.q) : undefined, action: req.query.action ? String(req.query.action) : undefined, page: Number(req.query.page) || 1, pageSize: Number(req.query.pageSize) || 30 })));
  app.get('/api/v1/admin/users', requirePermission(store, 'users:manage'), async (_req, res) => res.json({ users: await store.listUsers() }));
  app.patch('/api/v1/admin/users/:id/role', requirePermission(store, 'users:manage'), async (req, res) => { assertPrivileged(req); const input = toInput(roleRequest, req.body); const target = await store.findUserById(String(req.params.id)); assert(target, 404, 'USER_NOT_FOUND', 'User not found'); assert(target.id !== req.user!.id || input.role === 'super_admin', 409, 'SELF_ROLE_CHANGE_BLOCKED', 'You cannot remove your own admin access'); assert(req.user!.role === 'super_admin' || input.role !== 'super_admin', 403, 'SUPER_ADMIN_REQUIRED', 'Only a super admin can grant super-admin access'); const user = await store.setUserRole(target.id, input.role); await store.audit('admin.user_role_updated', { ...clientMeta(req), userId: req.user!.id, metadata: { targetUserId: target.id, previousRole: target.role, role: input.role } }); res.json({ user }); });

  app.get('/api/v1/admin/services', requirePermission(store, 'services:manage'), async (_req, res) => res.json({ services: await store.getServiceVisibility() }));
  app.patch('/api/v1/admin/services/:key/status', requirePermission(store, 'services:manage'), async (req, res) => { const key = String(req.params.key) as any; const input = toInput(z.object({ status: serviceStatusSchema, confirm: z.boolean().default(false) }), req.body); const current = (await store.getServiceVisibility()).find(item => item.key === key); assert(current, 404, 'SERVICE_NOT_FOUND', 'Service not found'); assert(input.status === current.status || input.confirm, 400, 'CONFIRMATION_REQUIRED', `Confirm changing ${current.label} visibility`); const service = await store.updateServiceVisibility(key, input.status, req.user!.id); await store.audit('admin.service_visibility_updated', { ...clientMeta(req), userId: req.user!.id, metadata: { service: key, previousStatus: current.status, status: input.status } }); res.json({ service }); });

  app.get('/api/v1/admin/customers/segments', requirePermission(store, 'customers:view'), async (_req,res)=>res.json({segments:await store.listCustomerSegments()}));
  app.post('/api/v1/admin/customers/segments', requirePermission(store, 'customers:view'), async (req,res)=>{const input=toInput(segmentInputSchema,req.body);const item=await store.createCustomerSegment({...input,createdBy:req.user!.id});res.status(201).json({segment:item,estimatedRecipients:await store.estimateSegment(item.rules)});});
  app.patch('/api/v1/admin/customers/segments/:id', requirePermission(store, 'customers:view'), async (req,res)=>{const input=toInput(segmentInputSchema.partial(),req.body);const item=await store.updateCustomerSegment(String(req.params.id),input);assert(item,404,'SEGMENT_NOT_FOUND','Segment not found');res.json({segment:item,estimatedRecipients:await store.estimateSegment(item.rules)});});
  app.post('/api/v1/admin/customers/segments/estimate', requirePermission(store, 'customers:view'), async (req,res)=>{const rules=z.record(z.unknown()).parse(req.body||{});res.json({estimatedRecipients:await store.estimateSegment(rules)});});
  app.get('/api/v1/admin/customers', requirePermission(store, 'customers:view'), async (req, res) => res.json(await store.listAdminCustomers({ q: req.query.q ? String(req.query.q) : undefined, status: req.query.status === 'active' || req.query.status === 'blocked' || req.query.status === 'pending' ? req.query.status : 'all', page: Number(req.query.page) || 1, pageSize: Number(req.query.pageSize) || 20 })));
  app.get('/api/v1/admin/customers/:id', requirePermission(store, 'customers:view'), async (req, res) => { const customer = await store.findAdminCustomer(String(req.params.id)); assert(customer, 404, 'CUSTOMER_NOT_FOUND', 'Customer not found'); res.json({ customer }); });
  app.post('/api/v1/admin/customers/:id/notes', requirePermission(store, 'customers:view'), async (req, res) => { const input = toInput(customerNoteRequest, req.body); const customer = await store.findUserById(String(req.params.id)); assert(customer && customer.role === 'customer', 404, 'CUSTOMER_NOT_FOUND', 'Customer not found'); const note = await store.addCustomerNote({ userId: customer.id, authorId: req.user!.id, note: input.note }); await store.audit('admin.customer_note_added', { ...clientMeta(req), userId: req.user!.id, metadata: { customerId: customer.id, noteId: note.id } }); res.status(201).json({ note }); });

  app.get('/api/v1/admin/payments', requirePermission(store, 'payments:view'), async (req, res) => res.json(await store.listAdminPayments({ q: req.query.q ? String(req.query.q) : undefined, status: paymentStatusSchema.safeParse(String(req.query.status || '')).success ? paymentStatusSchema.parse(String(req.query.status)) : 'all', provider: req.query.provider ? String(req.query.provider) : undefined, page: Number(req.query.page) || 1, pageSize: Number(req.query.pageSize) || 20 })));
  app.post('/api/v1/admin/payments/:id/refund', requirePermission(store, 'payments:manage'), async (_req, _res) => { throw new AppError(503, 'REFUNDS_NOT_CONFIGURED', 'Refunds require a configured gateway refund contract; no refund has been issued'); });

  app.get('/api/v1/admin/notifications/history', requirePermission(store, 'notifications:send'), async (req, res) => res.json(await store.listAdminNotifications({ q: req.query.q ? String(req.query.q) : undefined, status: ['queued','sent','failed','read'].includes(String(req.query.status)) ? String(req.query.status) as any : 'all', page: Number(req.query.page) || 1, pageSize: Number(req.query.pageSize) || 20 })));
  app.post('/api/v1/admin/notifications/:id/retry', requirePermission(store, 'notifications:send'), async (req, res) => { const notification = await store.findNotification(String(req.params.id)); assert(notification, 404, 'NOTIFICATION_NOT_FOUND', 'Notification not found'); assert(notification.status === 'failed', 409, 'NOTIFICATION_NOT_RETRYABLE', 'Only failed notifications can be retried'); try { if (notification.channels.includes('sms')) { assert(notification.recipient?.phone, 400, 'RECIPIENT_PHONE_MISSING', 'Recipient phone is not available'); await messaging.sendNotification('sms', notification.recipient.phone, notification.title, notification.message); } if (notification.channels.includes('email')) { assert(notification.recipient?.email, 400, 'RECIPIENT_EMAIL_MISSING', 'Recipient email is not available'); await messaging.sendNotification('email', notification.recipient.email, notification.title, notification.message); } const updated = await store.updateNotificationDelivery(notification.id, { status: 'sent', sentAt: new Date().toISOString(), failureReason: '' }); await store.audit('admin.notification_retried', { ...clientMeta(req), userId: req.user!.id, metadata: { notificationId: notification.id } }); res.json({ notification: updated }); } catch (error) { const reason = error instanceof Error ? error.message : 'Delivery failed'; const updated = await store.updateNotificationDelivery(notification.id, { status: 'failed', failureReason: reason }); throw error instanceof AppError ? error : new AppError(502, 'NOTIFICATION_RETRY_FAILED', 'Notification retry failed', config.isProduction ? undefined : { reason, notification: updated }); } });

  app.get('/api/v1/admin/campaigns', requirePermission(store, 'notifications:send'), async (req,res)=>res.json(await store.listCampaigns({q:req.query.q?String(req.query.q):undefined,status:['draft','scheduled','queued','processing','completed','partially_failed','failed','cancelled'].includes(String(req.query.status))?String(req.query.status) as any:'all',page:Number(req.query.page)||1,pageSize:Number(req.query.pageSize)||20})));
  app.post('/api/v1/admin/campaigns', requirePermission(store, 'notifications:send'), async (req,res)=>{const input=toInput(campaignInputSchema,req.body);const campaign=await store.createCampaign({...input,emailHtml:sanitizeEmailHtml(input.emailHtml),createdBy:req.user!.id});await store.audit('admin.campaign_created',{...clientMeta(req),userId:req.user!.id,metadata:{campaignId:campaign.id,channels:campaign.channels}});res.status(201).json({campaign});});
  app.get('/api/v1/admin/campaigns/templates', requirePermission(store, 'notifications:send'), async (req,res)=>res.json({templates:await store.listCampaignTemplates(req.query.type==='email'||req.query.type==='sms'||req.query.type==='in_app'?req.query.type:undefined)}));
  app.get('/api/v1/admin/campaigns/:id', requirePermission(store, 'notifications:send'), async (req,res)=>{const campaign=await store.findCampaign(String(req.params.id));assert(campaign,404,'CAMPAIGN_NOT_FOUND','Campaign not found');const recipients=await store.listCampaignRecipients(campaign.id,{page:Number(req.query.page)||1,pageSize:Number(req.query.pageSize)||50,status:req.query.recipientStatus?String(req.query.recipientStatus):undefined});res.json({campaign,recipients});});
  app.patch('/api/v1/admin/campaigns/:id', requirePermission(store, 'notifications:send'), async (req,res)=>{const input=toInput(campaignPatchSchema,req.body);const campaign=await store.updateCampaign(String(req.params.id),{...input,emailHtml:sanitizeEmailHtml(input.emailHtml)});assert(campaign,404,'CAMPAIGN_NOT_FOUND','Campaign not found');await store.audit('admin.campaign_updated',{...clientMeta(req),userId:req.user!.id,metadata:{campaignId:campaign.id,keys:Object.keys(input)}});res.json({campaign});});
  app.post('/api/v1/admin/campaigns/:id/send', requirePermission(store, 'notifications:send'), async (req,res)=>{const campaign=await store.findCampaign(String(req.params.id));assert(campaign,404,'CAMPAIGN_NOT_FOUND','Campaign not found');const queued=await store.queueCampaign(campaign.id,Array.isArray(req.body?.userIds)?req.body.userIds.map(String):undefined);assert(queued && queued.totalRecipients>0,400,'CAMPAIGN_NO_RECIPIENTS','No opted-in recipients match this campaign');await store.audit('admin.campaign_queued',{...clientMeta(req),userId:req.user!.id,metadata:{campaignId:campaign.id,recipients:queued.totalRecipients}});res.status(202).json({campaign:queued});});
  app.post('/api/v1/admin/campaigns/:id/retry', requirePermission(store, 'notifications:send'), async (req,res)=>{const campaign=await store.retryCampaignFailures(String(req.params.id));assert(campaign,404,'CAMPAIGN_NOT_FOUND','Campaign not found');await store.audit('admin.campaign_retry',{...clientMeta(req),userId:req.user!.id,metadata:{campaignId:campaign.id}});res.status(202).json({campaign});});
  app.post('/api/v1/admin/campaigns/:id/cancel', requirePermission(store, 'notifications:send'), async (req,res)=>{const campaign=await store.updateCampaign(String(req.params.id),{status:'cancelled'});assert(campaign,404,'CAMPAIGN_NOT_FOUND','Campaign not found');await store.audit('admin.campaign_cancelled',{...clientMeta(req),userId:req.user!.id,metadata:{campaignId:campaign.id}});res.json({campaign});});
  app.post('/api/v1/admin/campaigns/test', requirePermission(store, 'notifications:send'), async (req,res)=>{const input=toInput(campaignTestSchema,req.body);const destination=input.destination || req.user!.email || req.user!.phone;assert(destination,400,'TEST_DESTINATION_REQUIRED','Provide a test destination or set an admin email/phone');if(input.channel==='email')await messaging.sendEmail(destination,'Sadik Travels campaign test','This is a Sadik Travels campaign test.');else if(input.channel==='sms')await messaging.sendSms(destination,'Sadik Travels campaign test');else await store.createNotification({userId:req.user!.id,title:'Campaign test',message:'This is a Sadik Travels website notification test.',channels:['in_app'],status:'sent',createdBy:req.user!.id});res.json({sent:true,channel:input.channel});});
  app.post('/api/v1/admin/campaigns/templates', requirePermission(store, 'notifications:send'), async (req,res)=>{const input=toInput(templateInputSchema,req.body);const item=await store.createCampaignTemplate({...input,content:input.type==='email'?sanitizeEmailHtml(input.content)||'':input.content,createdBy:req.user!.id});res.status(201).json({template:item});});
  app.patch('/api/v1/admin/campaigns/templates/:id', requirePermission(store, 'notifications:send'), async (req,res)=>{const input=toInput(templateInputSchema.partial(),req.body);const item=await store.updateCampaignTemplate(String(req.params.id),{...input,content:input.content?sanitizeEmailHtml(input.content):input.content});assert(item,404,'TEMPLATE_NOT_FOUND','Template not found');res.json({template:item});});

  app.get('/api/v1/admin/settings', requirePermission(store, 'settings:manage'), async (_req, res) => { const saved = new Map((await store.getAdminSettings()).map(item => [item.key, item])); const settings = await Promise.all(SETTING_KEYS.map(async key => { const item = saved.get(key); if (item) return item; const value = await store.getSetting(key); return { key, configured: Boolean(value), secret: SETTING_SECRET_KEYS.has(key), ...(SETTING_SECRET_KEYS.has(key) ? { masked: value ? SECRET_MASK : '' } : { value: value ?? '' }) }; })); res.json({ settings }); });
  app.put('/api/v1/admin/settings', requirePermission(store, 'settings:manage'), async (req, res) => { assertPrivileged(req); const input = toInput(settingPatchSchema, req.body) as Record<string, string | undefined>; const patch = Object.fromEntries(Object.entries(input).filter(([key, value]) => value !== undefined && !(SETTING_SECRET_KEYS.has(key) && value === SECRET_MASK)).map(([key, value]) => [key, typeof value === 'boolean' ? String(value) : value])); await store.updateSettings(patch, req.user!.id); await store.audit('admin.settings_updated', { ...clientMeta(req), userId: req.user!.id, metadata: { keys: Object.keys(patch) } }); res.json({ settings: await store.getAdminSettings() }); });
  app.post('/api/v1/admin/settings/test-sms', requirePermission(store, 'settings:manage'), async (req, res) => { assertPrivileged(req); const input = toInput(messageTestRequest, req.body); const result = await messaging.sendSms(input.destination, input.message); res.json({ sent: true, result }); });
  app.post('/api/v1/admin/settings/test-email', requirePermission(store, 'settings:manage'), async (req, res) => { assertPrivileged(req); const input = toInput(messageTestRequest, req.body); const result = await messaging.sendEmail(input.destination, input.subject || 'Sadik Travels test email', input.message); res.json({ sent: true, result }); });

  // Booking assignment and lifecycle controls. Claiming is atomic at the database layer.
  app.get('/api/v1/admin/bookings', requirePermission(store, 'bookings:view'), async (req, res) => { const rawStatus = String(req.query.status || ''); const status = rawStatus === 'needs_review' ? 'needs_review' : (bookingStatusSchema.safeParse(rawStatus).success ? rawStatus as BookingStatus : 'all'); const vertical = verticalSchema.safeParse(String(req.query.vertical || '')); const result = await store.listAdminBookings({ q: req.query.q ? String(req.query.q) : undefined, status, vertical: vertical.success ? vertical.data : 'all', ownerId: req.query.ownerId ? String(req.query.ownerId) : undefined, page: Number(req.query.page) || 1, pageSize: Number(req.query.pageSize) || 20 }); res.json(result); });
  app.get('/api/v1/admin/bookings/:id', requirePermission(store, 'bookings:view'), async (req, res) => { const result = await store.listAdminBookings({ q: String(req.params.id), page: 1, pageSize: 1 }); const booking = result.bookings[0]; assert(booking, 404, 'BOOKING_NOT_FOUND', 'Booking not found'); res.json({ booking, history: await store.listBookingEvents(booking.id) }); });
  app.post('/api/v1/admin/bookings/:id/claim', requirePermission(store, 'bookings:manage'), async (req, res) => { const existing = await store.findBooking(String(req.params.id)); assert(existing, 404, 'BOOKING_NOT_FOUND', 'Booking not found'); if (existing.ownerId && existing.ownerId !== req.user!.id) throw new AppError(409, 'BOOKING_ALREADY_CLAIMED', 'This booking is already assigned to another operator'); const booking = await store.claimBooking(existing.id, req.user!.id); assert(booking, 409, 'BOOKING_ALREADY_CLAIMED', 'This booking is already assigned to another operator'); await store.audit('admin.booking_claimed', { ...clientMeta(req), userId: req.user!.id, metadata: { bookingId: existing.id } }); res.json({ booking }); });
  app.post('/api/v1/admin/bookings/:id/release', requirePermission(store, 'bookings:manage'), async (req, res) => { const existing = await store.findBooking(String(req.params.id)); assert(existing, 404, 'BOOKING_NOT_FOUND', 'Booking not found'); const booking = await store.releaseBooking(existing.id, req.user!.id, isPrivileged(req)); assert(booking, 403, 'BOOKING_OWNER_REQUIRED', 'Only the assigned operator can release this booking'); await store.audit('admin.booking_released', { ...clientMeta(req), userId: req.user!.id, metadata: { bookingId: existing.id } }); res.json({ booking }); });
  app.patch('/api/v1/admin/bookings/:id', requirePermission(store, 'bookings:manage'), async (req, res) => { const input = toInput(adminBookingPatchRequest, req.body); const existing = await store.findBooking(String(req.params.id)); assert(existing, 404, 'BOOKING_NOT_FOUND', 'Booking not found'); assert(isPrivileged(req) || existing.ownerId === req.user!.id, 403, 'BOOKING_OWNER_REQUIRED', 'Claim this booking before changing it'); if (input.ownerId !== undefined) { assertPrivileged(req); if (input.ownerId) { const assignee = await store.findUserById(input.ownerId); assert(assignee && ['manager', 'admin', 'super_admin', 'support', 'content_manager', 'finance'].includes(assignee.role) && assignee.status === 'active', 400, 'INVALID_ASSIGNEE', 'Choose an active admin or operator'); } } if (input.status && input.status !== existing.status) { assert(bookingTransitions[existing.status].includes(input.status), 409, 'INVALID_BOOKING_TRANSITION', `A ${existing.status} booking cannot move directly to ${input.status}`); } const action = input.ownerId !== undefined ? 'assignee_changed' : input.request !== undefined ? 'request_updated' : input.status ? 'status_changed' : 'note_added'; const booking = await store.updateAdminBooking(existing.id, { status: input.status, internalNote: input.internalNote, ownerId: input.ownerId, request: input.request }, req.user!.id, action); assert(booking, 404, 'BOOKING_NOT_FOUND', 'Booking not found'); await store.audit('admin.booking_updated', { ...clientMeta(req), userId: req.user!.id, metadata: { bookingId: existing.id, previousStatus: existing.status, status: input.status, previousOwnerId: existing.ownerId, ownerId: input.ownerId } }); res.json({ booking, history: await store.listBookingEvents(existing.id) }); });

  app.get('/api/v1/admin/tickets', requirePermission(store, 'support:manage'), async (req, res) => res.json({ tickets: await store.listSupportTickets({ status: ['open','pending','in_progress','waiting_customer','resolved','closed'].includes(String(req.query.status)) ? String(req.query.status) as any : 'all', q: req.query.q ? String(req.query.q) : undefined }) }));
  app.get('/api/v1/admin/tickets/:id', requirePermission(store, 'support:manage'), async (req, res) => { const ticket = await store.findSupportTicket(String(req.params.id)); assert(ticket, 404, 'TICKET_NOT_FOUND', 'Support ticket not found'); res.json({ ticket, messages: await store.listSupportMessages(ticket.id) }); });
  app.patch('/api/v1/admin/tickets/:id', requirePermission(store, 'support:manage'), async (req, res) => { const input = toInput(supportPatchRequest, req.body); if (input.assignedTo) { const assignee = await store.findUserById(input.assignedTo); assert(assignee && ['manager','admin','super_admin','support'].includes(assignee.role) && assignee.status === 'active', 400, 'INVALID_ASSIGNEE', 'Choose an active support operator'); } const ticket = await store.updateSupportTicket(String(req.params.id), input); assert(ticket, 404, 'TICKET_NOT_FOUND', 'Support ticket not found'); await store.audit('admin.ticket_updated', { ...clientMeta(req), userId: req.user!.id, metadata: { ticketId: ticket.id, status: ticket.status, priority: ticket.priority, assignedTo: ticket.assignedTo } }); res.json({ ticket }); });
  app.post('/api/v1/admin/tickets/:id/messages', requirePermission(store, 'support:manage'), async (req, res) => { const input = toInput(supportMessageRequest, req.body); const ticket = await store.findSupportTicket(String(req.params.id)); assert(ticket, 404, 'TICKET_NOT_FOUND', 'Support ticket not found'); const message = await store.createSupportMessage({ ticketId: ticket.id, authorId: req.user!.id, authorType: 'admin', message: input.message, internal: input.internal }); await store.audit('admin.ticket_message_added', { ...clientMeta(req), userId: req.user!.id, metadata: { ticketId: ticket.id, internal: input.internal } }); res.status(201).json({ message }); });

  app.get('/api/v1/admin/content', requirePermission(store, 'content:manage'), async (req, res) => { const type = contentTypeSchema.safeParse(String(req.query.type || '')); const status = contentStatusSchema.safeParse(String(req.query.status || '')); res.json({ content: await store.listContent({ type: type.success ? type.data : 'all', status: status.success ? status.data : 'all', q: req.query.q ? String(req.query.q) : undefined, includeArchived: true }) }); });
  app.post('/api/v1/admin/content', requirePermission(store, 'content:manage'), async (req, res) => { assertPrivileged(req); const input = toInput(contentInputSchema, req.body); const item = await store.createContent({ ...input, createdBy: req.user!.id }); await store.audit('admin.content_created', { ...clientMeta(req), userId: req.user!.id, metadata: { contentId: item.id, type: item.type } }); res.status(201).json({ content: item }); });
  app.patch('/api/v1/admin/content/:id', requirePermission(store, 'content:manage'), async (req, res) => { assertPrivileged(req); const input = toInput(contentPatchSchema, req.body); const item = await store.updateContent(String(req.params.id), input); assert(item, 404, 'CONTENT_NOT_FOUND', 'Content item not found'); await store.audit('admin.content_updated', { ...clientMeta(req), userId: req.user!.id, metadata: { contentId: item.id, type: item.type } }); res.json({ content: item }); });
  app.delete('/api/v1/admin/content/:id', requirePermission(store, 'content:manage'), async (req, res) => { assertPrivileged(req); const item = await store.archiveContent(String(req.params.id)); assert(item, 404, 'CONTENT_NOT_FOUND', 'Content item not found'); await store.audit('admin.content_archived', { ...clientMeta(req), userId: req.user!.id, metadata: { contentId: item.id } }); res.json({ content: item }); });

  app.get('/api/v1/admin/media', requirePermission(store, 'content:manage'), async (req, res) => res.json(await store.listMediaAssets({ q: req.query.q ? String(req.query.q) : undefined, folder: req.query.folder ? String(req.query.folder) : undefined, status: req.query.status === 'active' || req.query.status === 'archived' || req.query.status === 'failed' ? req.query.status : 'all', page: Number(req.query.page) || 1, pageSize: Number(req.query.pageSize) || 24 })));
  app.post('/api/v1/admin/media', requirePermission(store, 'content:manage'), rateLimit('media-upload', 20, 60), mediaUpload.single('file'), async (req, res) => { assert(req.file, 400, 'IMAGE_REQUIRED', 'Choose an image to upload'); const folder = toInput(mediaFolderSchema, String(req.body.folder || 'general')); const altText = typeof req.body.altText === 'string' ? req.body.altText : undefined; const uploaded = await media.upload(req.file.buffer, { folder, originalFilename: req.file.originalname, declaredMime: req.file.mimetype, altText }); let asset; try { asset = await store.createMediaAsset({ ...uploaded, status: 'active', uploadedBy: req.user!.id }); } catch (error) { await media.delete(uploaded.publicId).catch(() => undefined); throw error; } await store.audit('admin.media_uploaded', { ...clientMeta(req), userId: req.user!.id, metadata: { mediaId: asset.id, publicId: asset.publicId, folder: asset.folder } }); res.status(201).json({ media: asset }); });
  app.patch('/api/v1/admin/media/:id', requirePermission(store, 'content:manage'), async (req, res) => { const input = toInput(mediaPatchSchema, req.body); const asset = await store.updateMediaAsset(String(req.params.id), input); assert(asset, 404, 'MEDIA_NOT_FOUND', 'Media asset not found'); await store.audit('admin.media_updated', { ...clientMeta(req), userId: req.user!.id, metadata: { mediaId: asset.id, status: input.status } }); res.json({ media: asset }); });
  app.post('/api/v1/admin/media/:id/replace', requirePermission(store, 'content:manage'), rateLimit('media-replace', 20, 60), mediaUpload.single('file'), async (req, res) => { assert(req.file, 400, 'IMAGE_REQUIRED', 'Choose an image to upload'); const current = await store.findMediaAsset(String(req.params.id)); assert(current, 404, 'MEDIA_NOT_FOUND', 'Media asset not found'); const uploaded = await media.upload(req.file.buffer, { folder: current.folder.split('/').pop() || 'general', originalFilename: req.file.originalname, declaredMime: req.file.mimetype, altText: typeof req.body.altText === 'string' ? req.body.altText : current.altText }); let asset; try { asset = await store.updateMediaAsset(current.id, { ...uploaded, status: 'active' }); } catch (error) { await media.delete(uploaded.publicId).catch(() => undefined); throw error; } assert(asset, 500, 'MEDIA_UPDATE_FAILED', 'Image replacement failed'); await media.delete(current.publicId).catch(() => undefined); await store.audit('admin.media_replaced', { ...clientMeta(req), userId: req.user!.id, metadata: { mediaId: asset.id, previousPublicId: current.publicId, publicId: asset.publicId } }); res.json({ media: asset }); });
  app.delete('/api/v1/admin/media/:id', requirePermission(store, 'content:manage'), async (req, res) => { const current = await store.findMediaAsset(String(req.params.id)); assert(current, 404, 'MEDIA_NOT_FOUND', 'Media asset not found'); assert((await store.mediaReferenceCount(current.id)) === 0, 409, 'MEDIA_IN_USE', 'This image is still referenced by published content or a tour'); await store.updateMediaAsset(current.id, { status: 'archived' }); try { await media.delete(current.publicId); } catch { throw new AppError(502, 'MEDIA_DELETE_FAILED', 'The asset was archived but could not be removed from Cloudinary'); } await store.audit('admin.media_archived', { ...clientMeta(req), userId: req.user!.id, metadata: { mediaId: current.id, publicId: current.publicId } }); res.json({ media: await store.findMediaAsset(current.id) }); });

  app.get('/api/v1/admin/travel-agents', requirePermission(store, 'content:manage'), async (req,res)=>res.json(await store.listTravelAgents({q:req.query.q?String(req.query.q):undefined,status:req.query.status==='active'||req.query.status==='hidden'||req.query.status==='archived'?req.query.status:'all',department:req.query.department?String(req.query.department):undefined,featured:req.query.featured==='true'?true:req.query.featured==='false'?false:undefined,page:Number(req.query.page)||1,pageSize:Number(req.query.pageSize)||20})));
  app.get('/api/v1/admin/travel-agents/:id', requirePermission(store, 'content:manage'), async (req,res)=>{const agent=await store.findTravelAgent(String(req.params.id));assert(agent,404,'AGENT_NOT_FOUND','Travel agent not found');res.json({agent});});
  app.post('/api/v1/admin/travel-agents', requirePermission(store, 'content:manage'), async (req,res)=>{const input=toInput(agentInputSchema,req.body);const agent=await store.createTravelAgent({...input,createdBy:req.user!.id,updatedBy:req.user!.id});await store.audit('admin.travel_agent_created',{...clientMeta(req),userId:req.user!.id,metadata:{agentId:agent.id}});res.status(201).json({agent});});
  app.patch('/api/v1/admin/travel-agents/:id', requirePermission(store, 'content:manage'), async (req,res)=>{const input=toInput(agentPatchSchema,req.body);const agent=await store.updateTravelAgent(String(req.params.id),{...input,updatedBy:req.user!.id});assert(agent,404,'AGENT_NOT_FOUND','Travel agent not found');await store.audit('admin.travel_agent_updated',{...clientMeta(req),userId:req.user!.id,metadata:{agentId:agent.id,keys:Object.keys(input)}});res.json({agent});});
  app.delete('/api/v1/admin/travel-agents/:id', requirePermission(store, 'content:manage'), async (req,res)=>{const id=String(req.params.id);const current=await store.findTravelAgent(id);assert(current,404,'AGENT_NOT_FOUND','Travel agent not found');if(req.query.hard==='true'){assert(current.status==='archived',409,'AGENT_NOT_ARCHIVED','Archive the agent before permanent deletion');const deleted=await store.deleteTravelAgent(id);assert(deleted,409,'AGENT_DELETE_FAILED','Unable to delete travel agent');await store.audit('admin.travel_agent_deleted',{...clientMeta(req),userId:req.user!.id,metadata:{agentId:id}});return res.json({deleted:true});}const agent=await store.archiveTravelAgent(id);assert(agent,404,'AGENT_NOT_FOUND','Travel agent not found');await store.audit('admin.travel_agent_archived',{...clientMeta(req),userId:req.user!.id,metadata:{agentId:agent.id}});res.json({agent});});

  app.get('/api/v1/admin/tours', requirePermission(store, 'content:manage'), async (req, res) => { const filters: TourFilters = { q: req.query.q ? String(req.query.q) : undefined, country: req.query.country ? String(req.query.country) : undefined, tourType: req.query.tourType ? String(req.query.tourType) : undefined, status: req.query.status === 'draft' || req.query.status === 'published' || req.query.status === 'archived' ? req.query.status : undefined, sort: req.query.sort === 'price_asc' || req.query.sort === 'price_desc' ? req.query.sort : 'newest' }; res.json({ tours: await store.listTours(filters) }); });
  app.post('/api/v1/admin/tours', requirePermission(store, 'content:manage'), async (req, res) => { const input = toInput(tourInputSchema, req.body) as CreateTour; const tour = await store.createTour({ ...input, createdBy: req.user!.id }); await store.audit('admin.tour_created', { ...clientMeta(req), userId: req.user!.id, metadata: { tourId: tour.id } }); res.status(201).json({ tour }); });
  app.patch('/api/v1/admin/tours/:id', requirePermission(store, 'content:manage'), async (req, res) => { const input = toInput(tourPatchSchema, req.body) as UpdateTour; const tour = await store.updateTour(String(req.params.id), input); assert(tour, 404, 'TOUR_NOT_FOUND', 'Tour package not found'); await store.audit('admin.tour_updated', { ...clientMeta(req), userId: req.user!.id, metadata: { tourId: tour.id } }); res.json({ tour }); });
  app.delete('/api/v1/admin/tours/:id', requirePermission(store, 'content:manage'), async (req, res) => { const tour = await store.archiveTour(String(req.params.id)); assert(tour, 404, 'TOUR_NOT_FOUND', 'Tour package not found'); await store.audit('admin.tour_archived', { ...clientMeta(req), userId: req.user!.id, metadata: { tourId: tour.id } }); res.json({ tour }); });

  app.post('/api/v1/admin/notifications', requirePermission(store, 'notifications:send'), async (req, res) => {
    const input = toInput(notificationRequest, req.body);
    if (input.allUsers) assert(input.confirmMassSend, 400, 'MASS_SEND_CONFIRMATION_REQUIRED', 'Confirm that this notification should be sent to all active users');
    const normalizedRecipient = input.identity ? normalizeIdentity(input.identity).identity : undefined;
    const recipients = input.allUsers ? await store.listUsers() : [input.userId ? await store.findUserById(input.userId) : normalizedRecipient ? await store.findUserByIdentity(normalizedRecipient) : undefined].filter(Boolean);
    assert(recipients.length > 0, 404, 'RECIPIENT_NOT_FOUND', 'No notification recipient was found');
    const sent: string[] = []; const failed: Array<{ userId: string; reason: string }> = [];
    for (const recipient of recipients) {
      const user = recipient!;
      try {
        if (input.channels.includes('sms')) { assert(user.phone, 400, 'RECIPIENT_PHONE_MISSING', 'A phone number is required for SMS delivery'); await messaging.sendNotification('sms', user.phone, input.title, input.message); }
        if (input.channels.includes('email')) { assert(user.email, 400, 'RECIPIENT_EMAIL_MISSING', 'An email address is required for email delivery'); await messaging.sendNotification('email', user.email, input.title, input.message); }
        await store.createNotification({ userId: user.id, title: input.title, message: input.message, channels: input.channels, status: 'sent', sentAt: new Date().toISOString(), createdBy: req.user!.id }); sent.push(user.id);
      } catch (error) { const reason = error instanceof Error ? error.message : 'Delivery failed'; await store.createNotification({ userId: user.id, title: input.title, message: input.message, channels: input.channels, status: 'failed', failureReason: reason, createdBy: req.user!.id }); failed.push({ userId: user.id, reason }); }
    }
    await store.audit('admin.notification_sent', { ...clientMeta(req), userId: req.user!.id, metadata: { recipients: sent.length, failed: failed.length, channels: input.channels, allUsers: input.allUsers } }); res.status(201).json({ sent: sent.length, failed: failed.length, failures: failed.slice(0, 10), channels: input.channels });
  });

  // Booking creation: tour requests are persisted for operator review; all other verticals require a live supplier adapter.
  app.post('/api/v1/bookings', requireAuth(store), async (req, res) => {
    const input = toInput(bookingRequest, req.body);
    const payload = input.payload && typeof input.payload === 'object' && !Array.isArray(input.payload) ? input.payload as Record<string, unknown> : { value: input.payload };
    if (input.vertical === 'tour') {
      const tourPayload = toInput(tourBookingPayload, payload);
      const tour = await store.findTour(tourPayload.tourId);
      assert(tour && tour.status === 'published', 404, 'TOUR_NOT_FOUND', 'This tour package is no longer available');
      const booking = await store.createBooking({ userId: req.user!.id, vertical: 'tour', status: 'new', request: { ...tourPayload, tourId: tour.id, title: tour.title, priceBdt: tour.priceBdt } });
      await store.audit('booking.created', { ...clientMeta(req), userId: req.user!.id, metadata: { bookingId: booking.id, vertical: input.vertical, workflow: 'operator_review' } });
      res.status(201).json({ booking });
      return;
    }
    const booking = await store.createBooking({ userId: req.user!.id, vertical: input.vertical, request: payload, status: 'pending' });
    try {
      const providerResponse: any = await travel.reserve(input.vertical, { ...payload, bookingId: booking.id, customerId: req.user!.id });
      const status: BookingStatus = providerResponse?.status === 'confirmed' ? 'confirmed' : 'pending';
      const updated = await store.updateBooking(booking.id, { status, providerRef: providerResponse?.providerRef, response: providerResponse });
      await store.audit('booking.created', { ...clientMeta(req), userId: req.user!.id, metadata: { bookingId: booking.id, vertical: input.vertical } });
      res.status(201).json({ booking: updated ?? booking });
    } catch (error) { await store.updateBooking(booking.id, { status: 'failed', response: { error: 'provider_failure' } }); throw error; }
  });
  app.get('/api/v1/bookings', requireAuth(store), async (req, res) => res.json({ bookings: await store.listBookings(req.user!.id) }));
  app.post('/api/v1/bookings/track', rateLimit('booking-track', 30, 60), async (req, res) => { const input = toInput(trackBookingRequest, req.body); const identity = normalizeIdentity(input.identity).identity; const booking = await store.findBookingForTracking(input.bookingReference, identity); assert(booking, 404, 'BOOKING_NOT_FOUND', 'No booking matched that reference and contact'); res.json({ booking: { id: booking.id, vertical: booking.vertical, status: booking.status, providerRef: booking.providerRef, request: booking.request, response: booking.response, createdAt: booking.createdAt, updatedAt: booking.updatedAt } }); });
  app.get('/api/v1/bookings/:id', requireAuth(store), async (req, res) => { const booking = await store.findBooking(String(req.params.id), req.user!.id); assert(booking, 404, 'BOOKING_NOT_FOUND', 'Booking not found'); res.json({ booking }); });
  app.post('/api/v1/bookings/:id/cancel', requireAuth(store), async (req, res) => { const booking = await store.findBooking(String(req.params.id), req.user!.id); assert(booking, 404, 'BOOKING_NOT_FOUND', 'Booking not found'); assert(['new','reviewing','accepted','processing','pending','confirmed'].includes(booking.status), 409, 'BOOKING_NOT_CANCELLABLE', 'This booking cannot be cancelled at its current stage'); let result: unknown = { cancelledLocally: true }; if (booking.vertical !== 'tour' && booking.providerRef) result = await travel.cancel(booking.vertical, { bookingId: booking.id, providerRef: booking.providerRef, reason: (req.body as any)?.reason }); const updated = await store.updateBooking(booking.id, { status: 'cancelled', response: result }); await store.addBookingEvent({ bookingId: booking.id, actorId: req.user!.id, action: 'customer_cancelled', fromStatus: booking.status, toStatus: 'cancelled', note: (req.body as any)?.reason }); await store.audit('booking.cancelled', { ...clientMeta(req), userId: req.user!.id, metadata: { bookingId: booking.id } }); res.json({ booking: updated ?? booking }); });

  app.post('/api/v1/payments/intents', requireAuth(store), async (req, res) => { const input = toInput(paymentRequest, req.body); const booking = await store.findBooking(input.bookingId, req.user!.id); assert(booking, 404, 'BOOKING_NOT_FOUND', 'Booking not found'); assert(!['cancelled', 'rejected', 'new', 'reviewing', 'failed'].includes(booking.status), 409, 'BOOKING_NOT_PAYABLE', 'This booking is not ready for payment'); const paymentRecord = await store.createPayment({ bookingId: booking.id, userId: req.user!.id, provider: 'configured', amount: input.amount, currency: input.currency.toUpperCase(), status: 'created' }); const providerResponse: any = await payment.createIntent({ paymentId: paymentRecord.id, bookingId: booking.id, amount: input.amount, currency: input.currency.toUpperCase(), customerId: req.user!.id, returnUrl: `${config.appOrigin}/payment/return` }); const updated = await store.updatePayment(paymentRecord.id, { status: providerResponse?.status === 'paid' ? 'paid' : 'pending', transactionRef: providerResponse?.transactionRef, providerPayload: providerResponse }); res.status(201).json({ payment: updated ?? paymentRecord, checkoutUrl: providerResponse?.checkoutUrl }); });
  app.post('/api/v1/payments/webhook', async (req, res) => { assert(await payment.verifyWebhook(req.rawBody ?? Buffer.from(JSON.stringify(req.body ?? {})), req.header('x-payment-signature')), 401, 'INVALID_WEBHOOK', 'Invalid payment webhook signature'); const payload = req.body as { paymentId?: string; status?: string; transactionRef?: string }; assert(payload.paymentId && payload.status, 400, 'INVALID_WEBHOOK', 'Payment webhook payload is incomplete'); const status = payload.status === 'paid' ? 'paid' : payload.status === 'refunded' ? 'refunded' : payload.status === 'failed' ? 'failed' : 'pending'; const updated = await store.updatePayment(payload.paymentId, { status, transactionRef: payload.transactionRef, providerPayload: payload }); assert(updated, 404, 'PAYMENT_NOT_FOUND', 'Payment not found'); if (status === 'paid') { const booking = await store.findBooking(updated.bookingId); if (booking) { await store.updateBooking(updated.bookingId, { status: 'confirmed' }); await store.addBookingEvent({ bookingId: updated.bookingId, action: 'payment_confirmed', fromStatus: booking.status, toStatus: 'confirmed' }); } } res.json({ received: true }); });

  app.post('/api/v1/support/tickets', optionalAuth(store), rateLimit('support', 20, 60), async (req, res) => { const input = toInput(supportRequest, req.body); const ticket = await store.createSupportTicket({ ...input, userId: req.user?.id }); await store.audit('support.ticket_created', { ...clientMeta(req), userId: req.user?.id, metadata: { ticketId: ticket.id } }); res.status(201).json({ ticket: { id: ticket.id, status: ticket.status, createdAt: ticket.createdAt } }); });

  if (!config.serveStatic) app.get('/', (_req, res) => res.json({ service: 'Sadik Travels backend', status: 'online', health: '/healthz', ready: '/readyz' }));
  if (config.serveStatic) { app.get(/^\/admin(?:\/.*)?$/, (_req, res) => res.sendFile(path.join(config.publicDir, 'admin.html'))); app.use(express.static(config.publicDir, { index: 'index.html', maxAge: config.isProduction ? '1h' : 0 })); app.get(/^\/(?:search(?:\/.*)?|payment\/return)?$/, (_req, res) => res.sendFile(path.join(config.publicDir, 'index.html'))); }
  if (config.serveStatic) app.use((req, res, next) => { if (!req.path.startsWith('/api/')) return res.status(404).type('html').send(errorPageHtml(404)); next(); });
  app.use(notFound);
  app.use((error: unknown, req: Request, res: Response, _next: NextFunction) => {
    if (res.headersSent) return;
    const parseError = error instanceof SyntaxError && Number((error as any).status) === 400;
    const uploadError = error instanceof multer.MulterError;
    const normalized = error instanceof AppError ? error : error instanceof ZodError ? new AppError(400, 'VALIDATION_ERROR', 'Please check the submitted fields', error.flatten()) : uploadError && (error as any).code === 'LIMIT_FILE_SIZE' ? new AppError(413, 'IMAGE_TOO_LARGE', 'Image exceeds the maximum allowed size') : uploadError ? new AppError(400, 'IMAGE_UPLOAD_INVALID', 'Image upload failed. Please check the file and try again.') : parseError ? new AppError(400, 'INVALID_JSON', 'The request body contains invalid JSON') : new AppError(500, 'INTERNAL_ERROR', 'An unexpected error occurred');
    if ((req as any).log) (req as any).log.error({ err: error, requestId: req.requestId, code: normalized.code }, normalized.message);
    const safeExpose = normalized.expose || SAFE_PROVIDER_ERROR_CODES.has(normalized.code);
    if (config.serveStatic && !req.path.startsWith('/api/')) return res.status(normalized.statusCode).type('html').send(errorPageHtml(normalized.statusCode));
    res.status(normalized.statusCode).json({ error: { code: normalized.code, message: safeExpose ? normalized.message : 'An unexpected error occurred', ...(safeExpose && normalized.details ? { details: normalized.details } : {}) }, requestId: req.requestId });
  });
  return { app, store };
}
